### ISSUE TITLE
Handle missed billed records

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/csp-billing-adapter#65]
If the adapter is down or inoperable for some reason and misses billing records the records should be accumulated by billing cycle and the adapter update state in csp config accordingly.

The adapter could walk through each missed cycle and calculate what would've been billed and logged that while cleaning up the records in cache. This will be provided to the product and a notification shown to the user to resolve the issue.

How will the adapter state be reset if the resolution happens offline?

**Comment by rjschwei** [comment]
I think it is reasonable to expect that the customer requiring support, where this issue would surface, would also resolve the problem of not being able to bill. As such the offline potential settlement does not come into play. The issue with billing api access would be resolved and then going forward we are back in the expected work flow, i.e. records get reset on the billing interval. This process would then include resetting the "past due" records.

**Comment by smarlowucf** [comment]
That opens the door for an install to have permissions removed until support is needed. Then add permissions back. The adapter would assume things are good and clear out the failed state and missed periods. Which means it's all lost.

**Comment by rtamalin** [comment]
As per my comment in #64, if the adapter instance was unable to successfully perform meter_billing() requests for an extended period we could end up with lots of usage records and a target billing period in the past because we never got to run cache_meter_record() with an updated `next_bill_time`.

We could handle this by iteratively processing the target billing period, calculating the billable usage and associated dimensions, and then, if the target billing period is too old, add the info to an "unbilled periods" list in the cache, updating the `next_bill_time` appropriately, removing the processed usage records, and repeat until the target billing period is valid for billing purposes, and then resume normal operation...

**Comment by smarlowucf** [comment]
I think this is okay to close. Unless we want a separate check each run to remove any orphaned records. This should not happen anymore so not sure the value of an extra check?
