### ISSUE TITLE
Handle failure to save cache/csp-config

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/csp-billing-adapter#81]
It's possible that the adapter can take actions that require updating the cache or csp-config. If the adapter is unable to save the changes to either of these the data is lost. Thus the adapter should have retries and fault tolerance.

- For any save/get call that will hit a data store or external API the adapter should use retries with backoff in the event of failure
- If the retries are exhausted the adapter should have some other way to backup the state for the next run

**Comment by rtamalin** [comment]
When it comes to addressing the first requirement, namely adding operation retries, those can potentially be handled in either the core adapter code base, or in the plugin implementation. It would probably make more sense to do so in the core implementation, since then we only have to implement it once, and all deployment scenarios could benefit.

However, doing things that way in the core may complicate things for the second requirement, since alternate (semi-)persistent data stores would deployment solution specific, e.g. for the -local plugin, if we are getting errors for writing data to /var/lib/csp-billing-adapter (or wherever) in a cloud deployment, that likely would indicate a problem with the device backing the root file system, so the only alternative would be to write data to an additional attached volume, if there was one. Similarly for a -k8s deployment solution, alternative data store backups could be handled by writing to a file within the container file system, which could potentially be backed by a persistent HA volume attachment...

Unless we are talking about leveraging a parallel in-memory backup mechanism, implemented in the core, similar to the existing in-memory cache and csp_config testing support hook modules...

We could potentially make use of pluggy hook capabilities to register 2 or more data store implementations at the same time, but doing so could have some complicated potential failure matrices to deal with... E.g. requiring each data store to have a update timestamp (which they do), and logic to use the more recently updated version when there are differences between the multiple backing stores when doing running a get_cache() or get_csp_config() hook... And for save/update operations, if we have multiple data store implementations registered, how are things handled if only one of them raises an exception? Per https://pluggy.readthedocs.io/en/stable/#exception-handling and https://pluggy.readthedocs.io/en/stable/#hookwrappers it may be possible to leverage a hookwrapper to do some interesting things in this space, but will need investigation...
