### ISSUE TITLE
Add timestamp to logs

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/csp-billing-adapter#87]
Add a timestamp at the beginning of each log output:

```
2023-05-15T16:47:25.767|INFO|CSPBillingAdapter|Updating CSP config with: {'billing_api_access_ok': True, 'errors': [], 'timestamp': '2023-05-15T17:05:46.968960+00:00', 'expire': '2023-05-15T18:05:46.968960+00:00'}
```

**Comment by rtamalin** [comment]
Agreed that we definitely want timestamps in logs.

However, depending on how logs are going to be stored this could be a somewhat "redundant" timestamp... E.g. if the logs are ultimately being logged to the system logger, rather than to an on-disk logfile, to be accessed via journalctl, they will automatically get timestamps prepended to the logged message, making the inclusion of a timestamp in the log message itself redundant, though of course the journald message timestamps may not be exactly the same as the application ones.

For example if running interactively, it would be useful to see timestamps in any log meesages output, but if being run as a systemd service with output being sent to journald, it would potentially make the logged messages harder to read without significant benefit.

So, in the long run, this probably should be either a stream specific setting, or something handled by a hooked logger setup/configuration, or possibly both.

**Comment by smarlowucf** [comment]
The log format string could be part of config file. In k8s environment timestamp is missing.
